### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by pranjal-joshi** [DataSmoother/candlestick-patterns#2]
Hello,
Can you share the `pip` package name to install this?

**Comment by markusmaresch** [comment]
This is probably the easiest: git clone https://github.com/SpiralDevelopment/candlestick-patterns.git (or follow the green "Code" button ...

**Comment by pranjal-joshi** [comment]
But there's no setup.py file.
Is it supposed to be used by just downloading the source and putting in working directory to import?

**Comment by markusmaresch** [comment]
Yes - this is what I concluded after looking ..
